//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNACH.Biblioteca.Window.BibliotecaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Libro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        private System.Nullable<int> AñoPublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> AñoPublicacion {
            get {
                return this.AñoPublicacionField;
            }
            set {
                if ((this.AñoPublicacionField.Equals(value) != true)) {
                    this.AñoPublicacionField = value;
                    this.RaisePropertyChanged("AñoPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BibliotecaServiceReference.LibrosServiceSoap")]
    public interface LibrosServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BienvenidoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bienvenido", ReplyAction="*")]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponse Bienvenido(UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bienvenido", ReplyAction="*")]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponse> BienvenidoAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetLibrosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLibros", ReplyAction="*")]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponse GetLibros(UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLibros", ReplyAction="*")]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponse> GetLibrosAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento isbn del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateLibro", ReplyAction="*")]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponse CreateLibro(UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponse> CreateLibroAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento isbn del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLibro", ReplyAction="*")]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponse UpdateLibro(UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponse> UpdateLibroAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLibro", ReplyAction="*")]
        bool DeleteLibro(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteLibroAsync(System.Guid id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BienvenidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Bienvenido", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequestBody Body;
        
        public BienvenidoRequest() {
        }
        
        public BienvenidoRequest(UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BienvenidoRequestBody {
        
        public BienvenidoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BienvenidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BienvenidoResponse", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponseBody Body;
        
        public BienvenidoResponse() {
        }
        
        public BienvenidoResponse(UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BienvenidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BienvenidoResult;
        
        public BienvenidoResponseBody() {
        }
        
        public BienvenidoResponseBody(string BienvenidoResult) {
            this.BienvenidoResult = BienvenidoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLibrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLibros", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequestBody Body;
        
        public GetLibrosRequest() {
        }
        
        public GetLibrosRequest(UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLibrosRequestBody {
        
        public GetLibrosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLibrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponseBody Body;
        
        public GetLibrosResponse() {
        }
        
        public GetLibrosResponse(UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLibrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.Libro[] GetLibrosResult;
        
        public GetLibrosResponseBody() {
        }
        
        public GetLibrosResponseBody(UNACH.Biblioteca.Window.BibliotecaServiceReference.Libro[] GetLibrosResult) {
            this.GetLibrosResult = GetLibrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLibro", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequestBody Body;
        
        public CreateLibroRequest() {
        }
        
        public CreateLibroRequest(UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int añoPublicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string editorial;
        
        public CreateLibroRequestBody() {
        }
        
        public CreateLibroRequestBody(string isbn, string titulo, int añoPublicacion, string editorial) {
            this.isbn = isbn;
            this.titulo = titulo;
            this.añoPublicacion = añoPublicacion;
            this.editorial = editorial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponseBody Body;
        
        public CreateLibroResponse() {
        }
        
        public CreateLibroResponse(UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateLibroResult;
        
        public CreateLibroResponseBody() {
        }
        
        public CreateLibroResponseBody(bool CreateLibroResult) {
            this.CreateLibroResult = CreateLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLibro", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequestBody Body;
        
        public UpdateLibroRequest() {
        }
        
        public UpdateLibroRequest(UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int añoPublicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string editorial;
        
        public UpdateLibroRequestBody() {
        }
        
        public UpdateLibroRequestBody(System.Guid id, string isbn, string titulo, int añoPublicacion, string editorial) {
            this.id = id;
            this.isbn = isbn;
            this.titulo = titulo;
            this.añoPublicacion = añoPublicacion;
            this.editorial = editorial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponseBody Body;
        
        public UpdateLibroResponse() {
        }
        
        public UpdateLibroResponse(UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateLibroResult;
        
        public UpdateLibroResponseBody() {
        }
        
        public UpdateLibroResponseBody(bool UpdateLibroResult) {
            this.UpdateLibroResult = UpdateLibroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LibrosServiceSoapChannel : UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibrosServiceSoapClient : System.ServiceModel.ClientBase<UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap>, UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap {
        
        public LibrosServiceSoapClient() {
        }
        
        public LibrosServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibrosServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponse UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.Bienvenido(UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest request) {
            return base.Channel.Bienvenido(request);
        }
        
        public string Bienvenido() {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequestBody();
            UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponse retVal = ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).Bienvenido(inValue);
            return retVal.Body.BienvenidoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponse> UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.BienvenidoAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest request) {
            return base.Channel.BienvenidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoResponse> BienvenidoAsync() {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.BienvenidoRequestBody();
            return ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).BienvenidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponse UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.GetLibros(UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest request) {
            return base.Channel.GetLibros(request);
        }
        
        public UNACH.Biblioteca.Window.BibliotecaServiceReference.Libro[] GetLibros() {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequestBody();
            UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponse retVal = ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).GetLibros(inValue);
            return retVal.Body.GetLibrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponse> UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.GetLibrosAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest request) {
            return base.Channel.GetLibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosResponse> GetLibrosAsync() {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.GetLibrosRequestBody();
            return ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).GetLibrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponse UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.CreateLibro(UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest request) {
            return base.Channel.CreateLibro(request);
        }
        
        public bool CreateLibro(string isbn, string titulo, int añoPublicacion, string editorial) {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequestBody();
            inValue.Body.isbn = isbn;
            inValue.Body.titulo = titulo;
            inValue.Body.añoPublicacion = añoPublicacion;
            inValue.Body.editorial = editorial;
            UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponse retVal = ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).CreateLibro(inValue);
            return retVal.Body.CreateLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponse> UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.CreateLibroAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest request) {
            return base.Channel.CreateLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroResponse> CreateLibroAsync(string isbn, string titulo, int añoPublicacion, string editorial) {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.CreateLibroRequestBody();
            inValue.Body.isbn = isbn;
            inValue.Body.titulo = titulo;
            inValue.Body.añoPublicacion = añoPublicacion;
            inValue.Body.editorial = editorial;
            return ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).CreateLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponse UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.UpdateLibro(UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest request) {
            return base.Channel.UpdateLibro(request);
        }
        
        public bool UpdateLibro(System.Guid id, string isbn, string titulo, int añoPublicacion, string editorial) {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequestBody();
            inValue.Body.id = id;
            inValue.Body.isbn = isbn;
            inValue.Body.titulo = titulo;
            inValue.Body.añoPublicacion = añoPublicacion;
            inValue.Body.editorial = editorial;
            UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponse retVal = ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).UpdateLibro(inValue);
            return retVal.Body.UpdateLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponse> UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap.UpdateLibroAsync(UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest request) {
            return base.Channel.UpdateLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroResponse> UpdateLibroAsync(System.Guid id, string isbn, string titulo, int añoPublicacion, string editorial) {
            UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest inValue = new UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequest();
            inValue.Body = new UNACH.Biblioteca.Window.BibliotecaServiceReference.UpdateLibroRequestBody();
            inValue.Body.id = id;
            inValue.Body.isbn = isbn;
            inValue.Body.titulo = titulo;
            inValue.Body.añoPublicacion = añoPublicacion;
            inValue.Body.editorial = editorial;
            return ((UNACH.Biblioteca.Window.BibliotecaServiceReference.LibrosServiceSoap)(this)).UpdateLibroAsync(inValue);
        }
        
        public bool DeleteLibro(System.Guid id) {
            return base.Channel.DeleteLibro(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteLibroAsync(System.Guid id) {
            return base.Channel.DeleteLibroAsync(id);
        }
    }
}
